name: Deploy React App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
      
    - name: Add .nojekyll file
      run: touch .nojekyll
    - run: git add .nojekyll
    - run: git commit -m "Automatic Deploy action run by github-actions"
    - run: git push origin HEAD:gh-pages --force
